---
output:
  pdf_document: default
  html_document: default
---

```{r}
install.packages("tidyverse")
install.packages("ggplot2")
library(tidyverse)
library(ggplot2)
source("../utils.R")
```

```{r}
df <- readRDS("cases/cripto.rds")
```

```{r}
df_dogecoin = subset(df, name=="Dogecoin")
df_stellar = subset(df, name=="Stellar")
df_xrp = subset(df, name=="XRP")
```

```{r}
ggplot(df_dogecoin, aes(x=date, y=close)) +
  geom_line() +
  ggtitle("Evolução do preço de fechamento - Dogecoin") +
  xlab("Tempo (anos)") +
  ylab("Preço (R$)")

ggplot(df_stellar, aes(x=date, y=close)) +
  geom_line() +
  ggtitle("Evolução do preço de fechamento - Stellar") +
  xlab("Tempo (anos)") +
  ylab("Preço (R$)")

ggplot(df_xrp, aes(x=date, y=close)) +
  geom_line() +
  ggtitle("Evolução do preço de fechamento - XRP") +
  xlab("Tempo (anos)") +
  ylab("Preço (R$)")
```

```{r}
calc_returns = function(data) {
  for(i in 2:nrow(data)) {
    data$return[i] = log(data$close[i] / data$close[i-1])
  }
  
  clean_data = data[-1,]
  
  return (clean_data)
}
```

```{r}
plot_returns = function(data, title) {
  ggplot(data, aes(x=date, y=return * 100)) +
  geom_line() +
  ggtitle(title) +
  xlab("Tempo (anos)") +
  ylab("Retorno (%)")
}
```

```{r}
df_dogecoin$return = 0
df_stellar$return = 0
df_xrp$return = 0

df_dogecoin_ret = calc_returns(df_dogecoin)
df_stellar_ret = calc_returns(df_stellar)
df_xrp_ret = calc_returns(df_xrp)

plot_returns(df_dogecoin_ret, "Evolução do retorno - Dogecoin")
plot_returns(df_stellar_ret, "Evolução do retorno - Stellar")
plot_returns(df_xrp_ret, "Evolução do retorno - XRP")
```

```{r}
plot_bars = function(data, title) {
  ggplot(data, aes(substr(date, 1, 7))) +
  geom_bar() +
  ggtitle(title) + 
  theme(axis.text.x = element_text(angle = 90)) +
  ylab("Frequência") +
  xlab("Mês")
}
```

```{r}
df_dogecoin_filtered = filter(df_dogecoin_ret, return > 0.025)
df_stellar_filtered = filter(df_stellar_ret, return > 0.025)
df_xrp_filtered = filter(df_xrp_ret, return > 0.025)

plot_bars(df_dogecoin_filtered, "a")
plot_bars(df_stellar_filtered, "a")
plot_bars(df_xrp_filtered, "a")
```

```{r}
plot_histogram = function(data, aes_func, title) {
  print(round(sqrt(nrow(data)), digits = 0))
  ggplot(data, aes_func) +
  geom_histogram(bins = round(sqrt(nrow(data)), digits = 0)) +
  ggtitle(title) + 
  ylab("Frequência") +
  xlab("Retorno") #Alterar labels
}
```

```{r}
plot_histogram(df_dogecoin_ret, aes(return), "a")
plot_histogram(df_stellar_ret, aes(return), "a")
plot_histogram(df_xrp_ret, aes(return), "a")

plot_histogram(df_dogecoin, aes(close), "a")
plot_histogram(df_stellar, aes(close), "a")
plot_histogram(df_xrp, aes(close), "a")
```
```{r}
get_mode <- function(x) {
  ux <- unique(round(x, digits = 2))
  tab <- tabulate(match(x, ux))
  ux[tab == max(tab)]
}
```

```{r}
display_info <- function(data) {
  print(paste("Mean: ", mean(data)))
  print(paste("Median: ", median(data)))
  print(paste("Mode: ", get_mode(data)))
  print(paste("Variance: ", sample_var(data)))
  print(paste("Standard deviation: ", sample_stdev(data)))
}
```

```{r}
display_info(df_dogecoin_ret$return)
display_info(df_stellar_ret$return)
display_info(df_xrp_ret$return)
```

```{r}
student_error <- function(data, alpha) {
  n <- length(data)
  t <- qt(1 - alpha, n - 1)
  stdev <- sample_stdev(data)
  return (t * stdev/sqrt(n))
}
```

```{r}
#TERMINAR OS ICs E (provavelmente) FAZER CHI²
```

```{r}
df_dogecoin_ret_filtered = filter(df_dogecoin_ret, return > 0.025)
```

```{r}
dogecoin_proportion = nrow(df_dogecoin_ret_filtered) / nrow(df_dogecoin_ret)
dogecoin_proportion
```

```{r}
proportion_error <- function(proportion, n, alpha) {
  z <- qnorm(1 - alpha)
  return (z * sqrt(proportion * (1 - proportion) / n))
}
```

```{r}
normal_graph <- function(mean, sd, error, title, xlabel, ylabel) {
  x <- seq(-5 + mean, 5 + mean, by = .01)
  y <- dnorm(x, mean = mean, sd = sd)
  df_distr <- data.frame(x = x, y = y)
  ggplot(df_distr, aes(x = x, y = y)) +
    geom_point() +
    ggtitle(title) +
    xlab(xlabel) +
    ylab(ylabel) +
    geom_vline(xintercept = (mean - error)) +
    geom_vline(xintercept = (mean + error))
}
```


```{r}
error <- proportion_error(dogecoin_proportion, nrow(df_dogecoin_ret), 0.025)
paste("95% confidence error for Dogecoin:", round(error, 4))
paste("95% confidence interval for Dogecoin:", round(dogecoin_proportion - error, 4), "~",round(dogecoin_proportion + error, 4))

error <- proportion_error(dogecoin_proportion, nrow(df_dogecoin_ret), 0.05)
paste("90% confidence error for Dogecoin:", round(error, 4))
paste("90% confidence interval for Dogecoin:", round(dogecoin_proportion - error, 4), "~",round(dogecoin_proportion + error, 4))

error <- proportion_error(dogecoin_proportion, nrow(df_dogecoin_ret), 0.005)
paste("99% confidence error for Dogecoin:", round(error, 4))
paste("99% confidence interval for Dogecoin:", round(dogecoin_proportion - error, 4), "~",round(dogecoin_proportion + error, 4))
```

```{r}
dogecoin_var <- sample_var(df_dogecoin_ret$return)
stellar_var <- sample_var(df_stellar_ret$return)
xrp_var <- sample_var(df_xrp_ret$return)
dogecoin_var
```

```{r}
dogecoin_critical_value_a <- qchisq(0.025, nrow(df_dogecoin_ret) - 1)
dogecoin_critical_value_b <- qchisq(0.975, nrow(df_dogecoin_ret) - 1)

stellar_critical_value_a <- qchisq(0.025, nrow(df_stellar_ret) - 1)
stellar_critical_value_b <- qchisq(0.975, nrow(df_stellar_ret) - 1)

xrp_critical_value_a <- qchisq(0.025, nrow(df_xrp_ret) - 1)
xrp_critical_value_b <- qchisq(0.975, nrow(df_xrp_ret) - 1)
```

```{r}
dogecoin_interval <- c((nrow(df_dogecoin_ret) - 1) * dogecoin_var / dogecoin_critical_value_a, (nrow(df_dogecoin_ret) - 1) * dogecoin_var / dogecoin_critical_value_b)

stellar_interval <- c((nrow(df_stellar_ret) - 1) * stellar_var / stellar_critical_value_a, (nrow(df_stellar_ret) - 1) * stellar_var / stellar_critical_value_b)

xrp_interval <- c((nrow(df_xrp_ret) - 1) * xrp_var / xrp_critical_value_a, (nrow(df_xrp_ret) - 1) * xrp_var / xrp_critical_value_b)

paste("95% confidence interval for Dogecoin:", round(dogecoin_interval[1], 6), "~", round(dogecoin_interval[2], 6))
paste("95% confidence interval for Stellar:", round(stellar_interval[1], 6), "~", round(stellar_interval[2], 6))
paste("95% confidence interval for XRP:", round(xrp_interval[1], 6), "~", round(xrp_interval[2], 6))
```

```{r}
new_dogecoin_ret <- tail(df_dogecoin_ret, 20)
new_stellar_ret <- tail(df_stellar_ret, 20)
new_xrp_ret <- tail(df_xrp_ret, 20)
```

```{r}
new_dogecoin_var <- sample_var(new_dogecoin_ret$return)
new_stellar_var <- sample_var(new_stellar_ret$return)
new_xrp_var <- sample_var(new_xrp_ret$return)
```

```{r}
new_dogecoin_critical_value_a <- qchisq(0.025, nrow(new_dogecoin_ret) - 1)
new_dogecoin_critical_value_b <- qchisq(0.975, nrow(new_dogecoin_ret) - 1)

new_stellar_critical_value_a <- qchisq(0.025, nrow(new_stellar_ret) - 1)
new_stellar_critical_value_b <- qchisq(0.975, nrow(new_stellar_ret) - 1)

new_xrp_critical_value_a <- qchisq(0.025, nrow(new_xrp_ret) - 1)
new_xrp_critical_value_b <- qchisq(0.975, nrow(new_xrp_ret) - 1)
```

```{r}
new_dogecoin_interval <- c((nrow(new_dogecoin_ret) - 1) * new_dogecoin_var / new_dogecoin_critical_value_a, (nrow(new_dogecoin_ret) - 1) * new_dogecoin_var / new_dogecoin_critical_value_b)

new_stellar_interval <- c((nrow(new_stellar_ret) - 1) * new_stellar_var / new_stellar_critical_value_a, (nrow(new_stellar_ret) - 1) * new_stellar_var / new_stellar_critical_value_b)

new_xrp_interval <- c((nrow(new_xrp_ret) - 1) * new_xrp_var / new_xrp_critical_value_a, (nrow(new_xrp_ret) - 1) * new_xrp_var / new_xrp_critical_value_b)

paste("95% confidence interval for Dogecoin:", round(new_dogecoin_interval[1], 6), "~", round(new_dogecoin_interval[2], 6))
paste("95% confidence interval for Stellar:", round(new_stellar_interval[1], 6), "~", round(new_stellar_interval[2], 6))
paste("95% confidence interval for XRP:", round(new_xrp_interval[1], 6), "~", round(new_xrp_interval[2], 6))
```

```{r}
```



