```{r}
library(ggplot2)
```


```{r}
bundesliga <- readRDS("bundesliga.rds")
```


```{r separating-dortmund-data}
dortmund_home_df <- subset(bundesliga, HomeTeam == "Dortmund")
dortmund_away_df <- subset(bundesliga, AwayTeam == "Dortmund")

dortmund_goals_home <- dortmund_home_df$FullTimeHomeGoals
dortmund_goals_away <- dortmund_away_df$FullTimeAwayGoals
```


```{r boxplot}

data1 <- data.frame(
  Group = rep("Em casa", length(dortmund_goals_home)),
  Value = dortmund_goals_home
)

data2 <- data.frame(
  Group = rep("Fora de casa", length(dortmund_goals_away)),
  Value = dortmund_goals_away
)

# Combine data frames
data <- rbind(data1, data2)

# Create the boxplot
ggplot(data, aes(x = Group, y = Value, fill = Group)) +
  geom_boxplot() +
  labs(title = "Side-by-Side Boxplot",
       x = "Group",
       y = "Value")
```

```{r dortmund-summary}
"Em casa:"
print(summary(dortmund_goals_home))
"Fora de casa:"
print(summary(dortmund_goals_away))
```

---
output:
  pdf_document: default
  html_document: default
---

```{r}
install.packages("tidyverse")
install.packages("ggplot2")
library(tidyverse)
library(ggplot2)
source("../utils.R")
```

```{r}
df <- readRDS("bundesliga.rds")
df_dortmund = subset(df, HomeTeam=="Dortmund")
```

```{r}
normal_error <- function(alpha, n, pop_stdev) {
  z <- qnorm(1 - alpha)
  stdev <- pop_stdev
  return (z * stdev/sqrt(n))
}
```

```{r}
student_error <- function(data, alpha) {
  n <- length(data)
  t <- qt(1 - alpha, n - 1)
  stdev <- sample_stdev(data)
  return (t * stdev/sqrt(n))
}
```

```{r}
print_test <- function(test, sample_value, crit_value, crit_value2=NULL) {
  if(test == ">") {
    if(sample_value > crit_value) {
      print(paste("REJECT H0 - ", sample_value, " > ", crit_value))
    }
    
    else {
      print(paste("ACCEPT H0 - ", sample_value, " <= ", crit_value))
    }
  }
  
  else if(test == "<") {
    if(sample_value < crit_value) {
      print(paste("REJECT H0 - ", sample_value, " < ", crit_value))
    }
    
    else {
      print(paste("ACCEPT H0 - ", sample_value, " >= ", crit_value))
    }
  }
  
  else if(test == "!=" && !is.null(crit_value2)) {
    if(sample_value < crit_value || sample_value > crit_value2) {
      print(paste("REJECT H0 - ", sample_value, " is not between ", crit_value, " and ", crit_value2))
    }
    
    else {
      print(paste("ACCEPT H0 - ", crit_value, " <= ", sample_value, " <= ", crit_value2))
    }
  }
}
```

#Teste de Hip贸tese - Normal 95%
```{r}
dortmund_goal_sd = 0.5
dortmund_goal_mean = mean(df_dortmund$FullTimeHomeGoals)
dortmund_goal_error = (-1) * normal_error(0.05, length(df_dortmund$FullTimeHomeGoals), dortmund_goal_sd)

dortmund_goal_crit = dortmund_goal_error + 2.6

print_test("<", dortmund_goal_mean, dortmund_goal_crit)
```

#Teste de Hip贸tese - t-Student 95%
```{r}
dortmund_goal_mean = mean(df_dortmund$FullTimeHomeGoals)
dortmund_goal_error = (-1) * student_error(df_dortmund$FullTimeHomeGoals, 0.05)

dortmund_goal_crit = dortmund_goal_error + 2.6

print_test("<", dortmund_goal_mean, dortmund_goal_crit)
```

#Teste de Hip贸tese - Normal 99%
```{r}
dortmund_goal_sd = 0.5
dortmund_goal_mean = mean(df_dortmund$FullTimeHomeGoals)
dortmund_goal_error = (-1) * normal_error(0.01, length(df_dortmund$FullTimeHomeGoals), dortmund_goal_sd)

dortmund_goal_crit = dortmund_goal_error + 2.6

print_test("<", dortmund_goal_mean, dortmund_goal_crit)
```

#Teste de Hip贸tese - t-Student 99%
```{r}
dortmund_goal_mean = mean(df_dortmund$FullTimeHomeGoals)
dortmund_goal_error = (-1) * student_error(df_dortmund$FullTimeHomeGoals, 0.01)

dortmund_goal_crit = dortmund_goal_error + 2.6

print_test("<", dortmund_goal_mean, dortmund_goal_crit)
```