---
output:
pdf_document: default
html_document: default
---
```{r}
  install.packages("tidyverse")
  install.packages("ggplot2")
  library(tidyverse)
  library(ggplot2)
  source("../utils.R")
```

```{r}
  df <- readRDS("tratamento.rds")
```

```{r separating-dortmund-data}
  gf_df <- subset(df, MEIO == "GF")
  gc_df <- subset(df, MEIO == "GC")
  lj_df <- subset(df, MEIO == "LJ")
  cresc_gf <- gf_df$CRESCIMENTO
  cresc_gc <- gc_df$CRESCIMENTO
  cresc_lj <- lj_df$CRESCIMENTO
```

```{r boxplot}
  data1 <- data.frame(
    Group = rep("Crescimento - Gema Fresca", length(cresc_gf)),
    Value = cresc_gf
  )
  data2 <- data.frame(
    Group = rep("Crescimento - Gema Comercial", length(cresc_gc)),
    Value = cresc_gc
  )
  data3 <- data.frame(
    Group = rep("Crescimento - Low Jeinsen", length(cresc_lj)),
    Value = cresc_lj
  )
  # Combine data frames
  data <- rbind(data1, data2, data3)
  # Create the boxplot
  ggplot(data, aes(x = Group, y = Value, fill = Group)) +
  geom_boxplot() +
  labs(title = "Side-by-Side Boxplot",
  x = "Group",
  y = "Value") +
  ylim(0, 2.5)
```

```{r dortmund-summary}
  print(summary(cresc_gf))
  print(summary(cresc_gc))
  print(summary(cresc_lj))
```