---
output:
  pdf_document: default
  html_document: default
---

```{r}
install.packages("tidyverse")
install.packages("ggplot2")
library(tidyverse)
library(ggplot2)
source("../utils.R")
```

```{r}
df <- readRDS("vendas.rds")
```

```{r}
modelo = lm(vendas ~tv, data=df)

#Resíduos
plot(modelo)

#Regressão linear
plot(c(0,300), c(0,300), type = "n", xlab = "x", ylab = "y")
abline(modelo$coefficients[1], modelo$coefficients[2])
```

```{r}
summary(modelo)
#Ambos tiveram p-valores menor do que 0.05. Rejeita-se H0 - o modelo de regressão È significativo
#R² = 0.8122
```

```{r}
plot_histogram = function(data, aes_func, title) {
  print(round(sqrt(nrow(data)), digits = 0))
  ggplot(data, aes_func) +
  geom_histogram(bins = round(sqrt(nrow(data)), digits = 0)) +
  ggtitle(title) + 
  ylab("Frequência") +
  xlab("Retorno") #Alterar labels
}
```

```{r}
  df_residuals = data.frame (
    residuals = modelo$residuals
  )

  plot_histogram(df_residuals, aes(residuals), "Resíduos")
  
  paste("Média dos resíduos: ", mean(df_residuals$residuals))
```

```{r}
tv = data.frame(tv=sort(df$tv))

estimados_IC = predict(modelo, tv, interval = "confidence")
previstos_IP = predict(modelo, tv, interval = "prediction")

plot(estimados_IC[,1])
lines(estimados_IC[,2], col="#FF0000")
lines(estimados_IC[,3], col="#FF0000")
plot(previstos_IP[,1])
lines(previstos_IP[,2], col="#FF0000")
lines(previstos_IP[,3], col="#FF0000")
```

```{r}
  test = aov(vendas ~ tv, df)
  summary(test)
```
