---
output:
  pdf_document: default
  html_document: default
---

## Distribuição Amostral

```{r}
library(ggplot2)
source("../utils.R")
```

```{r}
df <- readRDS("spotify_modificada.rds")
```

```{r}
generate_new_samples_measures <- function(K, M) {
  samples_measures <<- data.frame(mean = numeric(),
                                 var = numeric())
  for (i in 1:M) {
    sample_indexes <- sample(nrow(df), K, replace = TRUE)
    new_sample  <<- df[sample_indexes[1:K], ]
    mean <- mean(new_sample$duration_ms)
    var <- sample_var(new_sample$duration_ms)
    new_row <- data.frame(mean = mean, var = var)
    samples_measures <<- rbind(samples_measures, new_row)
  }
}
```

```{r}
display_means_info <- function() {
  print(paste("Mean of Sample Means:", mean_of_sample_means))
  difference <- mean_of_sample_means - population_mean
  print(paste("Difference:", round(difference, digits = 2)))
  error <-
    (mean_of_sample_means - population_mean) / population_mean
  print(paste("Error:", round(error * 100, digits = 1), "%"))
}
```

```{r}
display_vars_info <- function() {
  print(paste("Mean of Sample Vars:", mean_of_sample_vars))
  difference <- mean_of_sample_vars - population_var
  print(paste("Difference:", round(difference, digits = 2)))
  error <- (mean_of_sample_vars - population_var) / population_var
  print(paste("Error:", round(error * 100, digits = 1), "%"))
}
```

```{r}
display_info <-
  function(K, M) {
    print(paste("Sample Size:", K))
    print(paste("Number of Samples:", M))
    
    display_means_info()
    display_vars_info()
    
    hist(samples_measures$mean,
         main = paste("Samples means for", M, "samples"),
         xlab = "Mean",
         breaks = 20)
    hist(samples_measures$var,
         main = paste("Samples variances for", M, "samples"),
         xlab = "Variance",
         breaks = 20)
    print("-------------------------------------------------")
  }
```

```{r}
calculate_new_sample <- function(K, M) {
  generate_new_samples_measures(K, M)
  mean_of_sample_means <<- mean(samples_measures$mean)
  mean_of_sample_vars <<- mean(samples_measures$var)
  display_info(K, M)
}
```

```{r}
calculate_population_info <- function() {
  population_mean <<- mean(df$duration_ms)
  population_var <<- populational_var(df$duration_ms)
  print(paste("Population Mean:", population_mean))
  print(paste("Population Var:", population_var))
  print("-------------------------------------------------")
}
```

```{r}
K <- 200L
calculate_population_info()
calculate_new_sample(K, 40L)
calculate_new_sample(K, 450L)
calculate_new_sample(K, 2600L)
```

## Intervalo de Confiança

```{r}
normal_error <- function(data, alpha, pop_stdev) {
  z <- qnorm(1 - alpha)
  n <- length(data)
  stdev <- pop_stdev
  return (z * stdev/sqrt(n))
}
```

```{r}
student_error <- function(data, alpha) {
  n <- length(data)
  t <- qt(1 - alpha, n - 1)
  stdev <- sample_stdev(data)
  return (t * stdev/sqrt(n))
}
```

## Gráfico da distribuição de probabilidade

```{r}
normal_graph <- function(mean, sd, error, title, xlabel, ylabel) {
  x <- seq(-5 + mean, 5 + mean, by = .01)
  y <- dnorm(x, mean = mean, sd = sd)
  df_distr <- data.frame(x = x, y = y)
  ggplot(df_distr, aes(x = x, y = y)) +
    geom_point() +
    ggtitle(title) +
    xlab(xlabel) +
    ylab(ylabel) +
    geom_vline(xintercept = (mean - error)) +
    geom_vline(xintercept = (mean + error))
}
```

## Cálculo do Erro - Normal - 95%

```{r}
df_new = subset(df, status=="Novo")
df_old = subset(df, status=="Velho")

sample_size = 450

###AQUI NEW SAMPLE
###ONLY EXECUTE these next lines when it's needed an all-new sample.
sample_new = df_new[sample(nrow(df_new), sample_size, replace = TRUE),]
sample_old = df_old[sample(nrow(df_old), sample_size, replace = TRUE),]

error_new_n = normal_error(sample_new$duration_ms / 60000, 0.025, 4.0)

error_old_n = normal_error(sample_old$duration_ms / 60000, 0.025, 7.0)

print(paste("Mean confidence interval for new musics sample (95%):", mean(sample_new$duration_ms / 60000), "+/-", error_new_n))

print(paste("Mean confidence interval for old musics sample (95%):", mean(sample_old$duration_ms / 60000), "+/-", error_old_n))

print(paste("Valor tabelado: ", qnorm(0.975)))

normal_graph(mean(sample_new$duration_ms / 60000), 4.0, error_new_n, "Distribuição Normal para Duração Músicas Novas - 95% de Confiança", "Duração", "Densidade de Probabilidade")

normal_graph(mean(sample_old$duration_ms / 60000), 7.0, error_old_n, "Distribuição Normal para Duração Músicas Velhas - 95% de Confiança", "Duração", "Densidade de Probabilidade")
```

## Cálculo do Erro - Normal - 90%

```{r}
error_new_n = normal_error(sample_new$duration_ms / 60000, 0.05, 4.0)

error_old_n = normal_error(sample_old$duration_ms / 60000, 0.05, 7.0)

print(paste("Mean confidence interval for new musics sample (90%):", mean(sample_new$duration_ms / 60000), "+/-", error_new_n))

print(paste("Mean confidence interval for old musics sample (90%):", mean(sample_old$duration_ms / 60000), "+/-", error_old_n))

print(paste("Valor tabelado: ", qnorm(0.950)))

normal_graph(mean(sample_new$duration_ms / 60000), 4.0, error_new_n, "Distribuição Normal para Duração Músicas Novas - 90% de Confiança", "Duração", "Densidade de Probabilidade")

normal_graph(mean(sample_old$duration_ms / 60000), 7.0, error_old_n, "Distribuição Normal para Duração Músicas Velhas - 90% de Confiança", "Duração", "Densidade de Probabilidade")
```

## Cálculo do Erro - Normal - 99%

```{r}
error_new_n = normal_error(sample_new$duration_ms / 60000, 0.005, 4.0)

error_old_n = normal_error(sample_old$duration_ms / 60000, 0.005, 7.0)

print(paste("Mean confidence interval for new musics sample (99%):", mean(sample_new$duration_ms / 60000), "+/-", error_new_n))

print(paste("Mean confidence interval for old musics sample (99%):", mean(sample_old$duration_ms / 60000), "+/-", error_old_n))

print(paste("Valor tabelado: ", qnorm(0.995)))

normal_graph(mean(sample_new$duration_ms / 60000), 4.0, error_new_n, "Distribuição Normal para Duração Músicas Novas - 99% de Confiança", "Duração", "Densidade de Probabilidade")

normal_graph(mean(sample_old$duration_ms / 60000), 7.0, error_old_n, "Distribuição Normal para Duração Músicas Velhas - 99% de Confiança", "Duração", "Densidade de Probabilidade")
```

## Cálculo do Erro - T-Student - 95%

```{r}
error_new_t = student_error(sample_new$duration_ms / 60000, 0.025)

error_old_t = student_error(sample_old$duration_ms / 60000, 0.025)

print(paste("Mean confidence interval for new musics sample (95%):", mean(sample_new$duration_ms / 60000), "+/-", error_new_t))

print(paste("Mean confidence interval for old musics sample (95%):", mean(sample_old$duration_ms / 60000), "+/-", error_old_t))

print(paste("GL:", (sample_size - 1), "; Valor tabelado:", qt(0.975, sample_size - 1)))
```

## Cálculo do Erro - T-Student - 90%

```{r}
error_new_t = student_error(sample_new$duration_ms / 60000, 0.05)

error_old_t = student_error(sample_old$duration_ms / 60000, 0.05)

print(paste("Mean confidence interval for new musics sample (90%):", mean(sample_new$duration_ms / 60000), "+/-", error_new_t))

print(paste("Mean confidence interval for old musics sample (90%):", mean(sample_old$duration_ms / 60000), "+/-", error_old_t))

print(paste("GL:", (sample_size - 1), "; Valor tabelado:", qt(0.950, sample_size - 1)))
```

## Cálculo do Erro - T-Student - 99%

```{r}
error_new_t = student_error(sample_new$duration_ms / 60000, 0.005)

error_old_t = student_error(sample_old$duration_ms / 60000, 0.005)

print(paste("Mean confidence interval for new musics sample (99%):", mean(sample_new$duration_ms / 60000), "+/-", error_new_t))

print(paste("Mean confidence interval for old musics sample (99%):", mean(sample_old$duration_ms / 60000), "+/-", error_old_t))

print(paste("GL:", (sample_size - 1), "; Valor tabelado:", qt(0.995, sample_size - 1)))
```