---
output:
  pdf_document: default
  html_document: default
---

```{r}
install.packages("tidyverse")
install.packages("ggplot2")
library(tidyverse)
library(ggplot2)
source("../utils.R")
```

```{r}
df <- readRDS("bundesliga.rds")
df_dortmund = subset(df, HomeTeam=="Dortmund")
```

```{r}
normal_error <- function(alpha, n, pop_stdev) {
  z <- qnorm(1 - alpha)
  stdev <- pop_stdev
  return (z * stdev/sqrt(n))
}
```

```{r}
student_error <- function(data, alpha) {
  n <- length(data)
  t <- qt(1 - alpha, n - 1)
  stdev <- sample_stdev(data)
  return (t * stdev/sqrt(n))
}
```

```{r}
chi_error <- function(data, alpha) {
  n <- length(data)
  chi <- qchisq(1 - alpha, n - 1)
  return (chi / (n - 1))
}
```

```{r}
print_test <- function(test, sample_value, crit_value, crit_value2=NULL) {
  if(test == ">") {
    if(sample_value > crit_value) {
      print(paste("REJECT H0 - ", sample_value, " > ", crit_value))
    }
    
    else {
      print(paste("ACCEPT H0 - ", sample_value, " <= ", crit_value))
    }
  }
  
  else if(test == "<") {
    if(sample_value < crit_value) {
      print(paste("REJECT H0 - ", sample_value, " < ", crit_value))
    }
    
    else {
      print(paste("ACCEPT H0 - ", sample_value, " >= ", crit_value))
    }
  }
  
  else if(test == "!=" && !is.null(crit_value2)) {
    if(sample_value < crit_value || sample_value > crit_value2) {
      print(paste("REJECT H0 - ", sample_value, " is not between ", crit_value, " and ", crit_value2))
    }
    
    else {
      print(paste("ACCEPT H0 - ", crit_value, " <= ", sample_value, " <= ", crit_value2))
    }
  }
}
```

#Teste de Hipótese - Normal 95%
```{r}
dortmund_goal_sd = 0.982
dortmund_goal_mean = mean(df_dortmund$FullTimeAwayGoals)
dortmund_goal_error = normal_error(0.05, length(df_dortmund$FullTimeAwayGoals), dortmund_goal_sd)

dortmund_goal_crit = 1 - dortmund_goal_error

dortmund_goal_crit2 = 1 + dortmund_goal_error

print_test("!=", dortmund_goal_mean, dortmund_goal_crit, dortmund_goal_crit2)
```

#Teste de Hipótese - t-Student 95%
```{r}
dortmund_goal_mean = mean(df_dortmund$FullTimeAwayGoals)
dortmund_goal_error = student_error(df_dortmund$FullTimeAwayGoals, 0.05)

dortmund_goal_crit = 1 - dortmund_goal_error

dortmund_goal_crit2 = 1 + dortmund_goal_error

print_test("!=", dortmund_goal_mean, dortmund_goal_crit, dortmund_goal_crit2)
```
